config/routes.rb
Rails.application.routes.draw do
  root 'calendars#index'
  resources :reservations, only: [:new, :create] do
    member do
      patch 'copy_reservename_to_name'
    end

    collection do
      get 'user'
    end
  end

  get '/calendars', to: 'calendars#index'
  delete '/reservations/:id/destroy', to: 'reservations#destroy', as: :destroy_reservation

  get '/admin', to: 'admin#index'
  get '/admin/reservations', to: 'admin#reservations'

  # ログイン用のルートを追加する
  post '/login', to: 'sessions#create', as: :login
  get '/admin/get_reservations_by_month', to: 'admin#get_reservations_by_month'

  post '/calendars/user_reservation', to: 'reservations#create_user_reservation', as: :user_reservation_create

  # ユーザフォームルートを追加
  get '/calendars/user_reservation', to: 'reservations#user', as: :user_reservation

  post '/admin/copy_reservations', to: 'admin#copy_reservations', as: :copy_reservations

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  
 
  end
  

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_calendar_variables, only: [:new, :create, :index]

  # 全予約の一覧
  def index
    @reservations = Reservation.all
  end

  # 新規予約作成ページ
  def new
    @reservation = Reservation.new(date: params[:date])
  end

  # 予約の作成
  def create
    @reservation = Reservation.new(reservation_params)
    set_reservation_name_based_on_category

    if @reservation.save
      delete_old_data # 保存後、古いデータを削除
      redirect_to admin_path(month: @reservation.date.strftime("%Y-%m"))
    else
      redirect_to new_reservation_path, alert: "何度やっても同じであれば、サーバ先の故障か改修が必要"
    end
  end

  # ユーザー向けの予約作成ページ
  def user
    @reservation = Reservation.new(
      date: params[:date],
      hour: params[:hour],
      minute: params[:minute]
      
    )
  end

  def user
    minute = params[:minute].to_s.rjust(2, '0')  # ここで左ゼロ埋め
    @reservation = Reservation.new(
      date: params[:date],
      hour: params[:hour],
      minute: minute  # 修正した minute を使用
    )
  end
  

  # 予約の削除
  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    head :no_content
  end

  # ユーザー向けの予約作成
  def create_user_reservation
    @reservation = Reservation.new(reservation_params)
    if handle_existing_reservation
      return # 既存の予約を処理した場合はここで終了
    end
  
    if @reservation.save
      delete_old_data # 保存後、古いデータを削除
      redirect_to calendars_path(month: @reservation.date.strftime("%Y-%m"))
    else
      # 保存が失敗した場合の処理
      redirect_to new_reservation_path, alert: "何度やっても同じであれば、サーバ先の故障か改修が必要"
    end
  end
    # 既存の"空き"という名前の予約を処理
  def handle_existing_reservation
    existing_reservation = Reservation.find_by(date: @reservation.date, hour: @reservation.hour, minute: @reservation.minute, name: '空き')
    if existing_reservation
      existing_reservation.update(name: 'ご予約受付中', reservename: @reservation.reservename, phone: @reservation.phone, menu: @reservation.menu)
      flash[:notice] = "ご予約を受け付けました、改めてご連絡いたします。\n数日経過してもご連絡が無い場合は、\nお手数ですが、ご一報いただけますと幸いです。"
      redirect_to calendars_path and return true
    end
    false
  end
  
  # reservenameをnameにコピー
  def copy_reservename_to_name
    @reservation = Reservation.find(params[:id])
    if @reservation
      @reservation.update(name: @reservation.reservename)
      render json: { message: 'Updated successfully.' }, status: :ok
    else
      render json: { error: 'Reservation not found.' }, status: :not_found
    end
  end

  private

  # カテゴリに基づいて予約の名前を設定
  def set_reservation_name_based_on_category
    if @reservation.category == '空き枠登録'
      @reservation.name = '空き'
    elsif @reservation.category == '予定変更'
      @reservation.name = '満員' if @reservation.fullhouse == 'ON'
      @reservation.name = '臨時休業' if @reservation.dayoff == 'ON'
    end
  end


  # 5ヶ月前と後のデータを削除
  def delete_old_data
    five_months_ago = 5.months.ago.beginning_of_month
    five_months_later = 5.months.from_now.end_of_month
    Reservation.where("date < ? OR date > ?", five_months_ago, five_months_later).delete_all
  end

  # 予約のパラメータを取得
  def reservation_params
    params.require(:reservation).permit(:date, :category, :hour, :minute, :name, :menu, :dayoff, :fullhouse, :reservename, :phone)
  end

  # カレンダーの変数を設定
  def set_calendar_variables
    @current_month = Date.today.at_beginning_of_month
    @weeks = generate_calendar_weeks(@current_month)
  end

  # カレンダーの週データを生成
  def generate_calendar_weeks(month)
    start_date = month.at_beginning_of_month
    end_date = month.at_end_of_month

    weeks = []
    current_date = start_date.beginning_of_week(:sunday).to_datetime

    while current_date <= end_date do
      week = []
      7.times do
        if current_date.month == month.month
          date = current_date.to_date
          reservations = Reservation.where(date: date)
          week << { date: date, reservations: reservations, holidays: japanese_holidays(date) }
        else
          week << nil
        end
        current_date += 1.day
      end
      weeks << week
    end

    weeks
  end

  # 日本の祝日を取得
  def japanese_holidays(date)
    holidays = Holidays.on(date, :jp)
    holidays.map { |holiday| holiday[:name] }
  end
end

app/views/reservations/new.html.erb
<!DOCTYPE html>
 <% flash.each do |alert, value| %>
    <div class="alert-<%= alert %>">
      <%= value %>
    </div>
  <% end %>

<html>
<head>
  <meta charset="UTF-8">
  <title>New Reservation</title>
  <%= link_to 'Back', 'javascript:history.back()', class: 'calendar-link' %>

  <link rel="stylesheet" href="styles.css">

</head>
<body>
  <h1>New Reservation</h1>
  <%= form_with model: @reservation, url: reservations_path, id: 'reservation_form' do |form| %>

    <div id="reservation_fields">
    
      <%= form.label :date, class: 'field' %>
      <%= form.date_field :date, readonly: true, id: 'reservation_date', style: 'border: none;' %>
      <br>

      <%= form.label :category, class: 'field' %>
      <%= form.select :category, ['予約登録', '空き枠登録', '予定変更'], { prompt: '' }, { required: true, id: 'category_select' } %>
      <br>

      <%= form.label :time, class: 'field' %>
      <%= form.select :hour, (0..23).map { |n| [format('%02d', n), n] }, { prompt: '時間' }, { required: true, id: 'time_select' } %>
      <%= form.select :minute, [0, 15, 30, 45].map { |n| [format('%02d', n), n] }, { prompt: '分' }, { required: true, id: 'minute_select' } %>
      <br>

      <%= form.label :name, class: 'field' %>
      <%= form.text_field :name, id: 'reservation_name', required: true, class: 'field' %>
      <br>

      <%= form.label :menu, class: 'field' %>
      <%= form.text_field :menu, id: 'reservation_menu', class: 'field' %>
      
      <br>

      <%= form.label :phone, class: 'field' %>
      <%= form.text_field :phone, id: 'reservation_phone', class: 'field' %>
      
      <br>


      <%= form.label :dayoff, class: 'field' %>
      <%= form.select :dayoff, ['ON'], { prompt: '' }, { class: 'field', id: 'dayoff_select' } %>
      <br>

      <%= form.label :fullhouse, class: 'field' %>
      <%= form.select :fullhouse, ['ON'], { prompt: '' }, { class: 'field', id: 'fullhouse_select' } %>
      <br>
    </div>

    <!-- 他の入力フィールドをここに追加 -->
    <br>
    <div class="actions">
      <%= form.submit '予約登録', id: 'reservation_button', disabled: true %>
      <%= button_tag '空き枠登録', id: 'empty_reservation_button', disabled: true %>
      <%= button_tag '予定変更', class: 'change-button', disabled: true %> 

    </div>

  <% end %>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var categorySelect = document.getElementById('category_select');
      var timeSelect = document.getElementById('time_select');
      var minuteSelect = document.getElementById('minute_select');
      var nameInput = document.getElementById('reservation_name');
      var menuInput = document.getElementById('reservation_menu');
      var phoneInput = document.getElementById('reservation_phone');
      var dayoffSelect = document.getElementById('dayoff_select');
      var fullhouseSelect = document.getElementById('fullhouse_select');
      var reservationButton = document.getElementById('reservation_button');
      var emptyReservationButton = document.getElementById('empty_reservation_button');
      var changeButton = document.querySelector('.change-button'); 

      function updateFieldsState() {
        var selectedCategory = categorySelect.value;

        timeSelect.disabled = true;
        minuteSelect.disabled = true;
        nameInput.disabled = true;
        menuInput.disabled = true;
        phoneInput.disabled = true;
        dayoffSelect.disabled = true;
        fullhouseSelect.disabled = true;
        reservationButton.disabled = true;
        emptyReservationButton.disabled = true;
        changeButton.disabled = true; 

        if (selectedCategory === '予約登録') {
          timeSelect.disabled = false;
          minuteSelect.disabled = false;
          nameInput.disabled = false;
          menuInput.disabled = false;
          phoneInput.disabled = false;
          reservationButton.disabled = false;
        } else if (selectedCategory === '空き枠登録') {
          timeSelect.disabled = false;
          minuteSelect.disabled = false;
          menuInput.disabled = false;
          emptyReservationButton.disabled = false;
        } else if (selectedCategory === '予定変更') {
          dayoffSelect.disabled = false;
          fullhouseSelect.disabled = false;
          changeButton.disabled = false; 
        }
      }

      categorySelect.addEventListener('change', function() {
        updateFieldsState();
      });

      updateFieldsState();
    });
  </script>
</body>
</html>

app/views/reservations/user.html.erb
<%= link_to 'Back', 'javascript:history.back()', class: 'calendar-link' %>
<h1>ご予約フォーム</h1>

<%= form_with(model: @reservation, url: user_reservation_path, method: :post) do |form| %>
  <!-- 予約日と時間の表示 -->
  <p>
    【日付】 
    <% date = Date.parse(params[:date] || @reservation.date) %>
    <%= date.strftime("%Y-%m-%d (%a)") %> <!-- URLパラメータまたは予約オブジェクトから日付を取得し、曜日を表示 -->
      <br> 
    【ご予約時間】 <%= params[:hour] || @reservation.hour %> : <%= params[:minute] || @reservation.minute.to_s.rjust(2, '0') %> <!-- URLパラメータまたは予約オブジェクトから時刻を表示 -->
  </p>

  <!-- 予約日と時間の隠しフィールド（フォーム送信時にサーバーへ渡される） -->
  <%= form.hidden_field :date, value: params[:date] || @reservation.date %>
  <%= form.hidden_field :hour, value: params[:hour] || @reservation.hour %>
  <%= form.hidden_field :minute, value: params[:minute] || @reservation.minute.to_s.rjust(2, '0') %>

  <!-- ご予約名の入力フィールド（必須） -->
  <%= form.label :reservename, 'ご予約名' %>
  <%= form.text_field :reservename, required: true %>
  
  <br>

  <!-- 電話番号の入力フィールド（必須） -->
  <%= form.label :phone, 'お電話番号' %> 
  <%= form.text_field :phone, required: true %>
  
  <br>

  <!-- メニューの入力フィールド（必須） -->
  <%= form.label :menu, 'メニュー' %>
  <%= form.text_field :menu, required: true %>
  
  <br>
  <br>

  <!-- 予約を送信するボタン -->
  <%= form.submit '予約する' %>
<% end %>